spring:
  devtools:
    livereload:
      enabled: false
    remote:
      restart:
        enabled: false
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    gateway:
      routes:
        - id: open
  mvc:
    favicon:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
#debug: true #调试模式，将会看到更多的日志信息。默认关闭
server:
  port: 6666

